services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NEXT_TELEMETRY_DISABLED: '1'
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - '3000:3000'
    volumes:
      - .:/workspace
      - openpot-node_modules:/workspace/node_modules
      - openpot-pnpm-store:/pnpm/store
    working_dir: /workspace
    command: >
      bash -lc "
      corepack pnpm install &&
      corepack pnpm dev --hostname 0.0.0.0
      "

volumes:
  openpot-node_modules:
  openpot-pnpm-store:
